name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rust-lang/setup-rust@v1
        with:
          rust-version: stable
          cache: true
      - name: Run tests
        run: cargo test --all --locked | tee test-results.txt
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.txt
