name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        run: cargo build --release

      - name: Package
        run: cargo package --allow-dirty --no-verify

      # Uncomment this step to publish to crates.io
      # - name: Publish to crates.io
      #   run: cargo publish --token ${{ secrets.CARGO_TOKEN }}

      - name: Archive release artifacts
        run: |
          mkdir -p artifacts
          cp -r target/release artifacts/
          tar -czf artifacts.tar.gz -C artifacts .

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts.tar.gz
